services:
  jobmanager:
    environment:
      - FLINK_ENV=dev
    depends_on:
      s3-init:
        condition: service_completed_successfully

  taskmanager:
    environment:
      - FLINK_ENV=dev
    depends_on:
      s3-init:
        condition: service_completed_successfully

  sql-gateway:
    environment:
      - FLINK_ENV=dev
    depends_on:
      s3-init:
        condition: service_completed_successfully